import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("image-generator page exposes generation, download and background actions", () => {
  const html = readFileSync("image-generator.html", "utf8");
  const script = readFileSync("js/image-generator.js", "utf8");
  const css = readFileSync("css/image-generator.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  assert.match(html, /<title>圖片生成器 · YuMeew<\/title>/);
  assert.match(html, />圖片生成器<span class="brand-sub">TEXT TO IMAGE<\/span>/);
  assert.match(html, /name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /id="image-prompt"[^>]*maxlength="2048"/);
  assert.doesNotMatch(html, /id="prompt-count"|0 \/ 2048/);
  assert.doesNotMatch(script, /prompt-count/);
  assert.match(html, /id="image-model"[^>]*class="setting-select"/);
  assert.match(html, /value="flux-2-klein-4b"[^>]*selected[^>]*>Flux\.2 Klein 4B<\/option>/);
  assert.match(html, /value="flux-2-klein-4b"[\s\S]*value="gpt-image-2\.5-flare">GPT-Image-2\.5 Flare<\/option>[\s\S]*value="gpt-image-2\.5-sunburst"/);
  assert.match(html, /value="gpt-image-2\.5-sunburst">GPT-Image-2\.5 Sunburst<\/option>/);
  assert.doesNotMatch(html, /提示詞會傳送至|model-provider-note|class="cloud-note"/);
  assert.match(html, /<span>API KEY<\/span>\s*<button id="model-api-key"[^>]*disabled>Free<\/button>/);
  assert.match(html, /class="prompt-actions">[\s\S]*class="generation-options"[\s\S]*id="image-model"[\s\S]*id="model-api-key"[\s\S]*id="generate-image"/);
  assert.match(html, /id="prompt-keywords"[^>]*type="text"/);
  assert.match(html, /id="compose-prompt"[^>]*class="export-button"[^>]*>組成題詞<\/button>/);
  assert.match(html, /id="generated-image-frame"/);
  assert.match(html, /id="generated-image-frame"[^>]*role="button"[^>]*tabindex="0"/);
  assert.match(html, /id="result-fullscreen-hint"[^>]*>⛶ 點擊全螢幕<\/span>/);
  assert.match(html, /1280 × 720/);
  assert.doesNotMatch(html, /每日早上 8 點（台灣時間）重置額度/);
  assert.match(html, /id="download-image"[^>]*disabled/);
  assert.match(html, /id="apply-background"[^>]*disabled/);
  assert.match(html, /id="open-image-history"[^>]*disabled>生成歷史<\/button>/);
  assert.match(html, /id="image-history-dialog"[\s\S]*最多保留最近 10 張圖片/);
  assert.match(html, /只有按下「套用主畫面背景」才會取代主畫面的背景素材/);
  assert.match(html, /id="generation-lock"[^>]*hidden/);
  assert.match(html, /id="flux-generation-confirm-dialog"[^>]*aria-labelledby="flux-generation-confirm-title"[\s\S]*此為公共資源，請勿濫用。[\s\S]*id="cancel-flux-generation"[^>]*>取消<\/button>[\s\S]*class="dialog-confirm"[^>]*type="submit"[^>]*>確定<\/button>/);
  assert.match(css, /aspect-ratio:\s*16\s*\/\s*9/);
  assert.match(css, /\.generated-image-frame:fullscreen/);
  assert.match(css, /\.generated-image-frame\.fullscreen-fallback/);
  assert.match(css, /body\.image-generator-body\s*\{[^}]*min-width:\s*0/);
  assert.match(css, /@media \(max-width:\s*800px\)/);
  assert.match(css, /\.prompt-actions\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 210px/);
  assert.match(css, /\.generation-options\s*\{[^}]*grid-template-columns:\s*minmax\(190px, 300px\) 200px/);
  assert.match(css, /\.model-api-key\s*\{[^}]*width:\s*200px/);
  assert.match(css, /\.model-api-key\s*\{[^}]*flex-direction:\s*row/);
  assert.match(css, /@media \(max-width:\s*800px\)[\s\S]*?\.prompt-actions\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /@media \(max-width:\s*560px\)/);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*?\.generation-options\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*?\.model-api-key\s*\{[^}]*width:\s*100%/);
  assert.match(css, /width:\s*100dvh;\s*height:\s*100vw/);
  assert.match(css, /rotate\(90deg\)/);
  assert.match(css, /@keyframes mobile-result-fullscreen-in/);
  assert.match(css, /\.autocomplete-row\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /\.result-actions\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/generate/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/autocomplete/);
  assert.match(script, /https:\/\/api\.openai\.com\/v1\/images\/generations/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /"Content-Type":\s*"application\/json"/);
  assert.match(script, /import \{ clientIdentityHeaders \} from "\.\/client-identity\.js"/);
  assert.equal((script.match(/\.\.\.clientIdentityHeaders\(\)/g) || []).length, 2);
  assert.match(html, /id="enhance-prompt"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /文字轉譯成Prompt/);
  assert.match(script, /const enhance = Boolean\(\$\("enhance-prompt"\)\.checked\)/);
  assert.match(script, /async function callFlux2Klein4B\(\{ prompt, enhance \}\)/);
  assert.match(script, /"flux-2-klein-4b": Object\.freeze\(\{[\s\S]*?label: "Flux\.2 Klein 4B"[\s\S]*?apiKey: "Free"[\s\S]*?publicResource: true[\s\S]*?call: callFlux2Klein4B/);
  assert.match(script, /"gpt-image-2\.5-sunburst": Object\.freeze\(\{[\s\S]*?label: "GPT-Image-2\.5 Sunburst"[\s\S]*?apiKey: "OpenAI"[\s\S]*?call: callGptImage25Sunburst/);
  assert.match(script, /"gpt-image-2\.5-flare": Object\.freeze\(\{[\s\S]*?label: "GPT-Image-2\.5 Flare"[\s\S]*?apiKey: "OpenAI"[\s\S]*?call: callGptImage25Flare/);
  assert.doesNotMatch(script, /model-provider-note|provider: "OpenAI Image API"/);
  assert.match(script, /async function callOpenAiImage\(\{ model, prompt, apiKey \}\)/);
  assert.match(script, /model: "gpt-image-2\.5-flare"/);
  assert.match(script, /Authorization: `Bearer \$\{apiKey\}`/);
  assert.match(script, /model: "gpt-image-2\.5-sunburst"/);
  assert.match(script, /size: "1280x720"/);
  assert.match(script, /output_format: "jpeg"/);
  assert.match(script, /image\?\.b64_json/);
  assert.match(script, /const modelId = \$\("image-model"\)\.value;\s*const model = IMAGE_MODELS\[modelId\]/);
  assert.match(script, /storedKey \? "已設定" : "未設定"/);
  assert.doesNotMatch(script, /maskApiKey/);
  assert.match(script, /\$\("image-model"\)\.addEventListener\("change", syncModelDetails\)/);
  assert.match(script, /\$\("model-api-key"\)\.addEventListener\("click", openApiKeyDialog\)/);
  assert.match(script, /saveApiKey\(model\.provider, model\.apiKey, value\)/);
  assert.match(script, /const storedKey = getApiKey\(model\.provider\)[\s\S]*api-key-input"\)\.value = storedKey\?\.value \|\| ""/);
  assert.match(script, /const response = await model\.call\(\{ prompt, enhance, apiKey \}\)/);
  assert.match(script, /function requestImageGeneration\(\)[\s\S]*model\?\.publicResource[\s\S]*flux-generation-confirm-dialog"\)\.showModal\(\)[\s\S]*generateImage\(\)/);
  assert.match(script, /function confirmFluxGeneration\(event\)[\s\S]*flux-generation-confirm-dialog"\)\.close\(\)[\s\S]*generateImage\(\)/);
  assert.match(script, /generate-image"\)\.addEventListener\("click", requestImageGeneration\)[\s\S]*flux-generation-confirm-form"\)\.addEventListener\("submit", confirmFluxGeneration\)/);
  assert.match(html, /id="api-key-input"[^>]*type="password"/);
  assert.match(html, /id="api-key-account-credits"[^>]*type="checkbox"[^>]*\/> 使用帳戶扣點/);
  assert.match(script, /usesAccountCredits\(modelId\) \? \(memberSignedIn \? "帳戶扣點" : "需登入"\)/);
  assert.match(script, /function canUseSelectedImageModel\(\)[\s\S]*usesAccountCredits\(modelId\)[\s\S]*return memberSignedIn/);
  assert.match(script, /function syncApiKeyCreditControls\(\)[\s\S]*accountOption\.disabled = !memberSignedIn[\s\S]*api-key-input"\)\.disabled = accountOption\.checked/);
  assert.match(script, /onAuthStateChange\(session =>[\s\S]*memberSignedIn = Boolean\(session\?\.user\)[\s\S]*syncModelDetails\(\)/);
  assert.doesNotMatch(html, /api-key-source|從其他模型複製/);
  assert.doesNotMatch(script, /copyApiKeyFromSource|syncApiKeySources|listApiKeys/);
  assert.match(script, /getApiKey\(model\.provider\)/);
  assert.match(script, /accountCredits && !memberSignedIn[\s\S]*請先登入會員帳號，再使用帳戶扣點/);
  assert.match(script, /\$\("image-model"\)\.disabled = value/);
  assert.match(script, /\$\("enhance-prompt"\)\.disabled = value/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt, enhance \}\)/);
  assert.match(script, /async function composePrompt\(\)/);
  assert.match(script, /async function toggleResultFullscreen\(\)/);
  assert.match(script, /resultFrame\.requestFullscreen\(\)/);
  assert.match(script, /resultFrame\.classList\.contains\("fullscreen-fallback"\)/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt \}\)/);
  assert.match(script, /\["completed", "prompt", "result", "text", "completion"\]/);
  assert.match(script, /body\?\.message \|\| body\?\.error/);
  assert.match(script, /\$\("image-prompt"\)\.value = result\.slice\(0, 2048\)/);
  assert.doesNotMatch(script, /\$\("image-prompt"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /\$\("prompt-keywords"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /searchParams\.set\("p"/);
  assert.match(script, /statusCode === 429/);
  assert.match(script, /body\.code !== "rate_limit_exceeded"/);
  assert.match(script, /操作過於頻繁，請在 \$\{retryAfter\} 秒後再試/);
  assert.match(script, /const limitedMessage = rateLimitMessage\(body\);[\s\S]*if \(limitedMessage\) throw Error\(limitedMessage\);/);
  assert.match(script, /const limitedMessage = rateLimitMessage\(errorBody\);[\s\S]*if \(model\.publicResource && isQuotaError/);
  assert.match(script, /今日圖片生成額度已用完，請於早上 8 點（台灣時間）額度重置後再試/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.match(script, /saveStoredMedia\("generated-image", cachedFile\)/);
  assert.match(script, /loadStoredMedia\("generated-image"\)/);
  assert.match(script, /const IMAGE_HISTORY_LIMIT = 10/);
  assert.match(script, /saveStoredValue\("image-generation-history"/);
  assert.match(script, /loadStoredValue\("image-generation-history"\)/);
  assert.match(script, /async function saveGenerationHistory\(blob, prompt, modelId\)[\s\S]*slice\(0, IMAGE_HISTORY_LIMIT\)/);
  assert.match(script, /open-image-history"\)\.addEventListener/);
  assert.match(script, /void restoreLastGeneratedImage\(\)/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  const mainHtml = readFileSync("index.html", "utf8");
  assert.match(mainHtml, /href="\.\/image-generator\.html"[^>]*>圖片生成器<\/a>/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"image-generator\.html"/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"image-generator\.html"/);
});

test("GitHub Pages build preserves the official custom domain", () => {
  assert.equal(readFileSync("CNAME", "utf8").trim(), "ezmusic.yustellar.idv.tw");
  assert.match(readFileSync("scripts/build.js", "utf8"), /"CNAME"/);
  assert.match(readFileSync("README.md", "utf8"), /https:\/\/ezmusic\.yustellar\.idv\.tw\//);
});
