import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

test('standalone subtitle editor has every referenced control and local page assets', () => {
  const html = readFileSync('subtitle-editor.html', 'utf8');
  const script = readFileSync('js/subtitle-editor.js', 'utf8');
  const transcription = readFileSync('js/song-transcription.js', 'utf8');
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\(['"]([^'"]+)['"]\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.doesNotMatch(script + transcription, /\b(XMLHttpRequest|sendBeacon|WebSocket)\s*\(/);
  assert.match(script, /saveStoredMedia\('subtitle'/);
  assert.match(script, /serializeSubtitles/);
  assert.doesNotMatch(script, /scrollCueToCenter|scrollIntoView/);
  assert.match(script, /createUndoHistory\(10\)/);
  assert.ok(ids.includes('undo-edit'));
  assert.ok(ids.includes('redo-edit'));
  assert.match(html, /id="undo-edit"[^>]*>↶ 復原<\/button>/);
  assert.match(html, /id="redo-edit"[^>]*>↷ 恢復<\/button>/);
  assert.match(html, /id="add-cue"[^>]*>＋<\/button>/);
  assert.match(html, /id="delete-cue"[^>]*>−<\/button>/);
  assert.match(html, /確定不保存修改直接返回主畫面？/);
  assert.ok(ids.includes('return-dialog'));
  assert.ok(ids.includes('return-dialog-cancel'));
  assert.ok(ids.includes('return-dialog-confirm'));
  for (const id of ['recognition-language', 'recognize-subtitles', 'recognition-progress-area', 'cancel-recognition', 'recognition-vocals-preview', 'recognition-vocals-audio', 'replace-subtitles-dialog', 'replace-subtitles-cancel', 'replace-subtitles-confirm']) {
    assert.ok(ids.includes(id), id);
  }
  for (const language of ['auto', 'zh', 'ja', 'en']) assert.match(html, new RegExp(`<option value="${language}">`));
  assert.match(html, /將會複寫目前的字幕，是否確認？/);
  assert.match(html, /只上傳分離後的人聲 WAV|原始音樂不會上傳/);
  assert.match(script, /new Worker\(new URL\('\.\/vocal-separator-worker\.js'/);
  assert.match(script, /model: 'spleeter'/);
  assert.match(script, /new OfflineContextClass\(1, Math\.ceil\(sourceBuffer\.duration \* 16000\), 16000\)/);
  assert.match(script, /encodePcm16Wav\(samples, transcriptionBuffer\.sampleRate\)/);
  assert.match(script, /showVocalsPreview\(wav\);\s+await uploadVocals\(samples, run\)/);
  assert.match(script, /URL\.revokeObjectURL\(recognition\.vocalsUrl\)/);
  assert.match(transcription, /form\.append\('audio', chunk\.blob, `chunk-\$\{chunk\.index\}\.wav`\)/);
  assert.match(transcription, /form\.append\('language', language\)/);
  assert.match(transcription, /form\.append\('offset', String\(chunk\.offset\)\)/);
  assert.match(transcription, /form\.append\('chunkIndex', String\(chunk\.index\)\)/);
  assert.match(script, /'https:\/\/lyrics-transcriber\.yustellar\.idv\.tw'/);
  assert.equal((transcription.match(/\bfetch\s*\(/g) || []).length, 1);
  assert.match(script, /parseSubtitles\(text, 'srt'\)/);
  assert.match(script, /MAX_RECOGNITION_FILE_SIZE = 150 \* 1024 \* 1024/);
  assert.match(script, /SEPARATOR_MAX_DURATION/);
  assert.doesNotMatch(script, /status\(message, 'error'\)/);
  assert.match(script, /function recognitionUnavailable\(message\) \{\s+setRecognitionProgress\(0, '無法開始辨識', message\)/);
  assert.doesNotMatch(script, /lyrics-recognition|recognize-lyrics|Whisper|startLyricsRecognition/);
  assert.equal((html.match(/data-time-field="start"/g) || []).length, 4);
  assert.equal((html.match(/data-time-field="end"/g) || []).length, 4);
  for (const delta of ['0.5', '0.1', '-0.5', '-0.1']) assert.match(html, new RegExp(`data-time-delta="${delta}"`));
});
