import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

test('standalone subtitle editor has every referenced control and only local assets', () => {
  const html = readFileSync('subtitle-editor.html', 'utf8');
  const script = readFileSync('js/subtitle-editor.js', 'utf8');
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\(['"]([^'"]+)['"]\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.doesNotMatch(script, /\b(fetch|XMLHttpRequest|sendBeacon|WebSocket)\s*\(/);
  assert.match(script, /saveStoredMedia\('subtitle'/);
  assert.match(script, /serializeSubtitles/);
  assert.doesNotMatch(script, /scrollCueToCenter|scrollIntoView/);
  assert.match(script, /createUndoHistory\(10\)/);
  assert.ok(ids.includes('undo-edit'));
  assert.ok(ids.includes('redo-edit'));
  assert.match(html, /id="undo-edit"[^>]*>↶ 復原<\/button>/);
  assert.match(html, /id="redo-edit"[^>]*>↷ 恢復<\/button>/);
  assert.match(html, /id="add-cue"[^>]*>＋<\/button>/);
  assert.match(html, /id="delete-cue"[^>]*>−<\/button>/);
  assert.match(html, /確定不保存修改直接返回主畫面？/);
  assert.ok(ids.includes('return-dialog'));
  assert.ok(ids.includes('return-dialog-cancel'));
  assert.ok(ids.includes('return-dialog-confirm'));
  assert.ok(ids.includes('recognize-lyrics'));
  assert.ok(ids.includes('lyrics-language'));
  assert.ok(ids.includes('lyrics-quality'));
  assert.ok(ids.includes('replace-lyrics-dialog'));
  assert.match(html, /覆蓋原本的歌詞？/);
  assert.match(html, /所有模型檔首次下載後都會自動保存在共用 IndexedDB/);
  assert.match(script, /new Worker\(new URL\('\.\/vocal-separator-worker\.js'/);
  assert.match(script, /new Worker\(new URL\('\.\/lyrics-recognition-worker\.js'/);
  assert.match(script, /recordHistory\(\);[\s\S]*state\.cues = normalizeCues\(cues/);
  const whisperWorker = readFileSync('js/lyrics-recognition-worker.js', 'utf8');
  assert.match(whisperWorker, /env\.useCustomCache = true/);
  assert.match(whisperWorker, /env\.customCache = indexedDbModelCache/);
  assert.match(whisperWorker, /whisper-base_timestamped/);
  assert.match(whisperWorker, /whisper-tiny_timestamped/);
  assert.match(whisperWorker, /device: 'webgpu'/);
  assert.match(whisperWorker, /device: 'wasm'/);
  assert.ok(existsSync('vendor/transformers-js/transformers.web.min.js'));
  assert.ok(existsSync('vendor/transformers-js/ort-wasm-simd-threaded.jsep.wasm'));
  assert.equal((html.match(/data-time-field="start"/g) || []).length, 4);
  assert.equal((html.match(/data-time-field="end"/g) || []).length, 4);
  for (const delta of ['0.5', '0.1', '-0.5', '-0.1']) assert.match(html, new RegExp(`data-time-delta="${delta}"`));
});
