import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { readSunoAudioResponse } from "../js/suno-source.js";

test("Suno tool page resolves, converts, previews and applies public audio", () => {
  const html = readFileSync("suno-tool.html", "utf8");
  const script = readFileSync("js/suno-tool.js", "utf8");
  const source = readFileSync("js/suno-source.js", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /id="suno-url"[^>]*placeholder="https:\/\/suno\.com\/s\/\.\.\."/);
  assert.match(html, /id="suno-player"[^>]*controls/);
  assert.match(html, /id="suno-download"[^>]*>下載音樂（WAV）</);
  assert.match(html, /id="suno-apply"[^>]*>套用到主畫面</);
  assert.match(html, /id="suno-apply-recognize"[^>]*>套用並辨識字幕</);
  assert.match(source, /model-proxy\.yustellar\.idv\.tw\/suno\/resolve/);
  assert.match(source, /\.\.\.clientIdentityHeaders\(\)/);
  assert.match(source, /readSunoAudioResponse\(await fetch\(metadata\.audioUrl/);
  assert.match(script, /new URLSearchParams\(location\.search\)\.get\("q"\)/);
  assert.match(script, /if \(shared\) \$\("suno-url"\)\.value = shared;/);
  assert.match(script, /prefillSharedUrlFromQueryString\(\);/);
  assert.match(script, /audioBlob = await convertToWav\(playableBlob\)/);
  assert.match(script, /URL\.createObjectURL\(audioBlob\)/);
  assert.match(source, /decryptSunoAudio\(encrypted, metadata\)/);
  assert.match(source, /crypto\.subtle\.decrypt\(\{ name: "AES-CTR", counter: iv, length: 128 \}/);
  assert.match(script, /convertMediaFile\(\{/);
  assert.match(script, /format: "wav"/);
  assert.match(script, /downloadBlob\(audioBlob, fileName\)/);
  assert.match(script, /new File\(\[audioBlob\], fileName, \{ type: "audio\/wav"/);
  assert.match(script, /saveStoredMedia\("audio", file\)/);
  assert.match(script, /location\.href = destination;/);
  assert.match(script, /applyToMain\("\.\/index\.html", \$\("suno-apply"\)\)/);
  assert.match(script, /applyToMain\("\.\/subtitle-editor\.html\?recognize=1", \$\("suno-apply-recognize"\)\)/);
  assert.doesNotMatch(script, /localStorage/);
  assert.match(readFileSync("index.html", "utf8"), /href="\.\/suno-tool\.html"[\s\S]*<strong>Suno 工具<\/strong>/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"suno-tool\.html"/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"suno-tool\.html"/);
});

test("encrypted Suno v5 audio accepts its binary CDN response", async () => {
  const bytes = new Uint8Array([1, 2, 3, 4]);
  const binaryResponse = () => new Response(bytes, { headers: { "Content-Type": "application/octet-stream" } });
  await assert.rejects(readSunoAudioResponse(binaryResponse()), /不是可播放的音樂檔案/);
  const blob = await readSunoAudioResponse(binaryResponse(), { allowEncryptedBinary: true });
  assert.equal(blob.size, bytes.length);
  assert.equal(blob.type, "application/octet-stream");
});
