import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("text-to-image page exposes generation, download and background actions", () => {
  const html = readFileSync("text-to-image.html", "utf8");
  const script = readFileSync("js/text-to-image.js", "utf8");
  const css = readFileSync("css/text-to-image.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /id="image-prompt"[^>]*maxlength="2048"/);
  assert.match(html, /id="prompt-keywords"[^>]*type="text"/);
  assert.match(html, /id="compose-prompt"[^>]*>組成題詞<\/button>/);
  assert.match(html, /id="generated-image-frame"/);
  assert.match(html, /1280 × 720/);
  assert.match(html, /每日早上 8 點（台灣時間）重置額度/);
  assert.match(html, /id="download-image"[^>]*disabled/);
  assert.match(html, /id="apply-background"[^>]*disabled/);
  assert.match(html, /只有按下「套用主畫面背景」才會取代瀏覽器保存的背景素材/);
  assert.match(html, /id="generation-lock"[^>]*hidden/);
  assert.match(css, /aspect-ratio:\s*16\s*\/\s*9/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/generate/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/autocomplete/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /"Content-Type":\s*"application\/json"/);
  assert.match(html, /id="enhance-prompt"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /文字轉譯成Prompt/);
  assert.match(script, /const enhance = Boolean\(\$\("enhance-prompt"\)\.checked\)/);
  assert.match(script, /\$\("enhance-prompt"\)\.disabled = value/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt, enhance \}\)/);
  assert.match(script, /async function composePrompt\(\)/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt \}\)/);
  assert.match(script, /\["completed", "prompt", "result", "text", "completion"\]/);
  assert.match(script, /body\?\.message \|\| body\?\.error/);
  assert.match(script, /\$\("image-prompt"\)\.value = result\.slice\(0, 2048\)/);
  assert.doesNotMatch(script, /\$\("image-prompt"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /\$\("prompt-keywords"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /searchParams\.set\("p"/);
  assert.match(script, /statusCode === 429/);
  assert.match(script, /今日圖片生成額度已用完，請於早上 8 點（台灣時間）額度重置後再試/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.doesNotMatch(script.slice(script.indexOf("async function generateImage"), script.indexOf('$("image-prompt")')), /saveStoredMedia/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  const mainHtml = readFileSync("index.html", "utf8");
  assert.match(mainHtml, /href="\.\/text-to-image\.html"[^>]*>文生圖<\/a>/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"text-to-image\.html"/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"text-to-image\.html"/);
});

test("GitHub Pages build preserves the official custom domain", () => {
  assert.equal(readFileSync("CNAME", "utf8").trim(), "ezmusic.yustellar.idv.tw");
  assert.match(readFileSync("scripts/build.js", "utf8"), /"CNAME"/);
  assert.match(readFileSync("README.md", "utf8"), /https:\/\/ezmusic\.yustellar\.idv\.tw\//);
});
