import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("text-to-video page provides a model-ready generation workspace", () => {
  const html = readFileSync("text-to-video.html", "utf8");
  const script = readFileSync("js/text-to-video.js", "utf8");
  const css = readFileSync("css/text-to-video.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /<title>文生影 · YuMeew<\/title>/);
  assert.doesNotMatch(html, /video-keywords|compose-video-prompt|題詞詞語|enhance-video-prompt|文字轉譯成 Prompt/);
  assert.match(html, /id="video-prompt"[^>]*maxlength="2048"/);
  assert.match(html, /id="video-resolution"/);
  assert.match(html, /id="video-duration"/);
  assert.match(html, /id="video-ratio"/);
  assert.match(html, /id="video-model"[^>]*class="setting-select"[\s\S]*value="MiniMax-H3"[^>]*selected>MiniMax H3<\/option>/);
  assert.match(html, /value="MiniMax-H3-Max">MiniMax H3 Max<\/option>/);
  assert.match(html, /id="video-api-key"[^>]*>未設定<\/button>/);
  assert.doesNotMatch(html, /影片模型與 API 尚未設定，後續加入模型後即可啟用生成/);
  assert.match(html, /id="generate-video"[^>]*disabled>▶ 生成影片<\/button>/);
  assert.match(html, /id="confirm-video-generation-dialog"[^>]*aria-labelledby="confirm-video-generation-title"/);
  assert.match(html, /影片生成會消耗 MiniMax 帳戶額度，是否確定開始生成？/);
  assert.match(html, /id="cancel-video-generation"[^>]*>取消<\/button>/);
  assert.match(html, /<button class="dialog-confirm" type="submit">確認生成<\/button>/);
  assert.match(html, /id="generated-video"[^>]*controls[^>]*playsinline[^>]*hidden/);
  assert.match(html, /id="download-video"[^>]*disabled/);
  assert.match(html, /id="apply-video-background"[^>]*disabled/);
  assert.match(css, /#video-prompt\s*\{[^}]*height:\s*224px/);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*#video-prompt\s*\{[^}]*height:\s*300px/);
  assert.match(css, /\.video-prompt-field\s*\{[^}]*margin:\s*12px 0 28px/);
  assert.match(script, /applyTheme\(settings\.mode, settings\.theme\)/);
  assert.match(script, /"MiniMax-H3": Object\.freeze\(\{[^}]*label: "MiniMax H3"[^}]*resolutions: \["768P", "2K"\][^}]*minimumDuration: 4/);
  assert.match(script, /"MiniMax-H3-Max": Object\.freeze\(\{[^}]*label: "MiniMax H3 Max"[^}]*resolutions: \["480P", "768P"\][^}]*minimumDuration: 5/);
  assert.match(script, /saveApiKey\(modelId, model\.label, value\)/);
  assert.match(script, /listApiKeys\(\)\.filter\(key => key\.id !== modelId\)/);
  assert.match(html, /id="video-api-key-dialog"/);
  assert.match(script, /https:\/\/minimax-proxy\.yustellar\.idv\.tw\/video/);
  assert.match(script, /CREATE_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /QUERY_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /DOWNLOAD_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /content: \[\{ type: "text", text: prompt \}\]/);
  assert.doesNotMatch(script, /AUTOCOMPLETE_URL|requestCompletedPrompt|enhance-video-prompt/);
  assert.match(script, /JSON\.stringify\(\{ apiKey, taskId \}\)/);
  assert.match(script, /apiKey,\s*payload: \{/);
  assert.match(script, /fetch\(DOWNLOAD_VIDEO_URL, \{[\s\S]*body: JSON\.stringify\(\{ url: remoteUrl \}\)/);
  assert.match(script, /code === 1008 \|\| \/insufficient balance\/i\.test\(message\)/);
  assert.match(script, /目前 MiniMax API KEY 所屬帳戶餘額不足（1008），請充值或更換 API KEY。/);
  assert.match(script, /code === 2013 && \/TokenPlan\|Credit\.\*MiniMax-H3\/i\.test\(message\)/);
  assert.match(script, /目前使用的 MiniMax Token Plan／Credit Key 不支援 H3 系列（2013）/);
  assert.match(html, /MiniMax H3 系列須使用一般 Pay-as-you-go API KEY；Token Plan／Credit Key 不支援/);
  assert.match(script, /miniMaxError\(body, response\.ok \? "" : `MiniMax API 回傳 \$\{response\.status\}`\)/);
  assert.match(script, /async function pollVideoTask\(taskId, apiKey, signal\)/);
  assert.match(script, /generate-video"\)\.addEventListener\("click", openGenerateConfirmation\)/);
  assert.match(script, /confirm-video-generation-form"\)\.addEventListener\("submit", confirmVideoGeneration\)/);
  assert.match(script, /taskState === "succeeded"/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.match(script, /saveStoredMedia\("generated-video", cachedFile\)/);
  assert.match(script, /loadStoredMedia\("generated-video"\)/);
  assert.match(script, /void restoreLastGeneratedVideo\(\)/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  assert.match(readFileSync("index.html", "utf8"), /href="\.\/text-to-video\.html"[^>]*>文生影<\/a>/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"text-to-video\.html"/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"text-to-video\.html"/);
});
