import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("text-to-image page exposes generation, download and background actions", () => {
  const html = readFileSync("text-to-image.html", "utf8");
  const script = readFileSync("js/text-to-image.js", "utf8");
  const css = readFileSync("css/text-to-image.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  assert.match(html, /name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /id="image-prompt"[^>]*maxlength="2048"/);
  assert.doesNotMatch(html, /id="prompt-count"|0 \/ 2048/);
  assert.doesNotMatch(script, /prompt-count/);
  assert.match(html, /id="image-model"[^>]*class="setting-select"/);
  assert.match(html, /value="flux-2-klein-4b"[^>]*selected[^>]*>Flux\.2 Klein 4B<\/option>/);
  assert.match(html, /value="flux-2-klein-4b"[\s\S]*value="gpt-image-2\.5-flare">GPT-Image-2\.5 Flare<\/option>[\s\S]*value="gpt-image-2\.5-sunburst"/);
  assert.match(html, /value="gpt-image-2\.5-sunburst">GPT-Image-2\.5 Sunburst<\/option>/);
  assert.doesNotMatch(html, /提示詞會傳送至|model-provider-note|class="cloud-note"/);
  assert.match(html, /<span>API KEY<\/span>\s*<button id="model-api-key"[^>]*disabled>Free<\/button>/);
  assert.match(html, /class="prompt-actions">[\s\S]*class="generation-options"[\s\S]*id="image-model"[\s\S]*id="model-api-key"[\s\S]*id="generate-image"/);
  assert.match(html, /id="prompt-keywords"[^>]*type="text"/);
  assert.match(html, /id="compose-prompt"[^>]*class="export-button"[^>]*>組成題詞<\/button>/);
  assert.match(html, /id="generated-image-frame"/);
  assert.match(html, /id="generated-image-frame"[^>]*role="button"[^>]*tabindex="0"/);
  assert.match(html, /id="result-fullscreen-hint"[^>]*>⛶ 點擊全螢幕<\/span>/);
  assert.match(html, /1280 × 720/);
  assert.doesNotMatch(html, /每日早上 8 點（台灣時間）重置額度/);
  assert.match(html, /id="download-image"[^>]*disabled/);
  assert.match(html, /id="apply-background"[^>]*disabled/);
  assert.match(html, /只有按下「套用主畫面背景」才會取代瀏覽器保存的背景素材/);
  assert.match(html, /id="generation-lock"[^>]*hidden/);
  assert.match(css, /aspect-ratio:\s*16\s*\/\s*9/);
  assert.match(css, /\.generated-image-frame:fullscreen/);
  assert.match(css, /\.generated-image-frame\.fullscreen-fallback/);
  assert.match(css, /body\.text-to-image-body\s*\{[^}]*min-width:\s*0/);
  assert.match(css, /@media \(max-width:\s*800px\)/);
  assert.match(css, /\.prompt-actions\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 210px/);
  assert.match(css, /\.generation-options\s*\{[^}]*grid-template-columns:\s*minmax\(190px, 300px\) 200px/);
  assert.match(css, /\.model-api-key\s*\{[^}]*width:\s*200px/);
  assert.match(css, /\.model-api-key\s*\{[^}]*flex-direction:\s*row/);
  assert.match(css, /@media \(max-width:\s*800px\)[\s\S]*?\.prompt-actions\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /@media \(max-width:\s*560px\)/);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*?\.generation-options\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /@media \(max-width:\s*560px\)[\s\S]*?\.model-api-key\s*\{[^}]*width:\s*100%/);
  assert.match(css, /width:\s*100dvh;\s*height:\s*100vw/);
  assert.match(css, /rotate\(90deg\)/);
  assert.match(css, /@keyframes mobile-result-fullscreen-in/);
  assert.match(css, /\.autocomplete-row\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(css, /\.result-actions\s*\{\s*grid-template-columns:\s*1fr/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/generate/);
  assert.match(script, /https:\/\/flux-klein-worker\.yustellar\.idv\.tw\/autocomplete/);
  assert.match(script, /https:\/\/api\.openai\.com\/v1\/images\/generations/);
  assert.match(script, /method:\s*"POST"/);
  assert.match(script, /"Content-Type":\s*"application\/json"/);
  assert.match(html, /id="enhance-prompt"[^>]*type="checkbox"[^>]*checked/);
  assert.match(html, /文字轉譯成Prompt/);
  assert.match(script, /const enhance = Boolean\(\$\("enhance-prompt"\)\.checked\)/);
  assert.match(script, /async function callFlux2Klein4B\(\{ prompt, enhance \}\)/);
  assert.match(script, /"flux-2-klein-4b": Object\.freeze\(\{[\s\S]*?label: "Flux\.2 Klein 4B"[\s\S]*?apiKey: "Free"[\s\S]*?call: callFlux2Klein4B/);
  assert.match(script, /"gpt-image-2\.5-sunburst": Object\.freeze\(\{[\s\S]*?label: "GPT-Image-2\.5 Sunburst"[\s\S]*?apiKey: "OpenAI"[\s\S]*?call: callGptImage25Sunburst/);
  assert.match(script, /"gpt-image-2\.5-flare": Object\.freeze\(\{[\s\S]*?label: "GPT-Image-2\.5 Flare"[\s\S]*?apiKey: "OpenAI"[\s\S]*?call: callGptImage25Flare/);
  assert.doesNotMatch(script, /model-provider-note|provider: "OpenAI Image API"/);
  assert.match(script, /async function callOpenAiImage\(\{ model, prompt, apiKey \}\)/);
  assert.match(script, /model: "gpt-image-2\.5-flare"/);
  assert.match(script, /Authorization: `Bearer \$\{apiKey\}`/);
  assert.match(script, /model: "gpt-image-2\.5-sunburst"/);
  assert.match(script, /size: "1280x720"/);
  assert.match(script, /output_format: "jpeg"/);
  assert.match(script, /image\?\.b64_json/);
  assert.match(script, /const modelId = \$\("image-model"\)\.value;\s*const model = IMAGE_MODELS\[modelId\]/);
  assert.match(script, /storedKey \? "已設定" : "未設定"/);
  assert.doesNotMatch(script, /maskApiKey/);
  assert.match(script, /\$\("image-model"\)\.addEventListener\("change", syncModelDetails\)/);
  assert.match(script, /\$\("model-api-key"\)\.addEventListener\("click", openApiKeyDialog\)/);
  assert.match(script, /saveApiKey\(modelId, model\.label, value\)/);
  assert.match(script, /const response = await model\.call\(\{ prompt, enhance, apiKey \}\)/);
  assert.match(html, /id="api-key-input"[^>]*type="password"/);
  assert.match(html, /id="api-key-source"[^>]*class="setting-select"/);
  assert.match(script, /listApiKeys\(\)\.filter\(key => key\.id !== modelId\)/);
  assert.match(script, /\$\("api-key-source"\)\.addEventListener\("change", copyApiKeyFromSource\)/);
  assert.match(script, /\$\("api-key-input"\)\.value = source\.value/);
  assert.match(script, /\$\("image-model"\)\.disabled = value/);
  assert.match(script, /\$\("enhance-prompt"\)\.disabled = value/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt, enhance \}\)/);
  assert.match(script, /async function composePrompt\(\)/);
  assert.match(script, /async function toggleResultFullscreen\(\)/);
  assert.match(script, /resultFrame\.requestFullscreen\(\)/);
  assert.match(script, /resultFrame\.classList\.contains\("fullscreen-fallback"\)/);
  assert.match(script, /body:\s*JSON\.stringify\(\{ prompt \}\)/);
  assert.match(script, /\["completed", "prompt", "result", "text", "completion"\]/);
  assert.match(script, /body\?\.message \|\| body\?\.error/);
  assert.match(script, /\$\("image-prompt"\)\.value = result\.slice\(0, 2048\)/);
  assert.doesNotMatch(script, /\$\("image-prompt"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /\$\("prompt-keywords"\)\.addEventListener\("keydown"/);
  assert.doesNotMatch(script, /searchParams\.set\("p"/);
  assert.match(script, /statusCode === 429/);
  assert.match(script, /今日圖片生成額度已用完，請於早上 8 點（台灣時間）額度重置後再試/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.match(script, /saveStoredMedia\("generated-image", cachedFile\)/);
  assert.match(script, /loadStoredMedia\("generated-image"\)/);
  assert.match(script, /void restoreLastGeneratedImage\(\)/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  const mainHtml = readFileSync("index.html", "utf8");
  assert.match(mainHtml, /href="\.\/text-to-image\.html"[^>]*>文生圖<\/a>/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"text-to-image\.html"/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"text-to-image\.html"/);
});

test("GitHub Pages build preserves the official custom domain", () => {
  assert.equal(readFileSync("CNAME", "utf8").trim(), "ezmusic.yustellar.idv.tw");
  assert.match(readFileSync("scripts/build.js", "utf8"), /"CNAME"/);
  assert.match(readFileSync("README.md", "utf8"), /https:\/\/ezmusic\.yustellar\.idv\.tw\//);
});
