import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("video generator page provides a model-ready generation workspace", () => {
  const html = readFileSync("video-generator.html", "utf8");
  const script = readFileSync("js/video-generator.js", "utf8");
  const css = readFileSync("css/video-generator.css", "utf8");
  const globalCss = readFileSync("css/style.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /<title>影片生成器 · YuMeew<\/title>/);
  assert.match(html, /<meta name="viewport" content="width=1280" \/>/);
  assert.match(html, /<a class="brand" href="\.\/" data-confirm-return/);
  assert.doesNotMatch(html, /video-keywords|compose-video-prompt|題詞詞語|enhance-video-prompt|文字轉譯成 Prompt/);
  assert.match(html, /<div id="video-prompt"[^>]*class="resource-editor"[^>]*contenteditable="true"[^>]*aria-label="影片細節"/);
  assert.doesNotMatch(html, />影片描述<\/label>|加入影片描述|等待輸入影片描述/);
  assert.match(html, /<details id="video-description-panel" class="panel prompt-panel video-description-panel" open>[\s\S]*<summary[^>]*>影片細節<\/summary>[\s\S]*id="video-prompt"[\s\S]*<\/details>\s*<details id="video-settings-panel" class="panel prompt-panel video-settings-panel">/);
  assert.match(html, /<summary class="video-collapsible-summary">生成設定<\/summary>/);
  assert.match(html, /<details id="video-result-panel" class="panel result-panel video-result-panel">[\s\S]*生成結果[\s\S]*<\/details>/);
  assert.doesNotMatch(html, /<details id="(?:video-settings-panel|video-result-panel)"[^>]*\sopen(?:\s|>)/);
  assert.match(html, /id="open-film-style"[^>]*>全片風格<\/button>\s*<button id="preview-video-prompt"[^>]*>預覽題詞<\/button>[\s\S]*id="open-character-template"[\s\S]*id="open-video-prompt-builder"[\s\S]*id="video-prompt"/);
  assert.doesNotMatch(html, /video-prompt-footer/);
  assert.match(html, /id="open-video-prompt-builder"[^>]*>新增分鏡<\/button>/);
  assert.match(html, /id="open-character-template"[^>]*>人物模板<\/button>/);
  assert.match(html, /id="video-prompt"[\s\S]*class="video-project-actions"[\s\S]*id="export-video-project"[^>]*>匯出設定<\/button>[\s\S]*id="select-video-project"[^>]*>匯入設定<\/button>/);
  assert.match(html, /id="video-project-input"[^>]*accept="\.zip,application\/octet-stream"[^>]*hidden/);
  assert.match(html, /id="export-video-project-dialog"[\s\S]*id="export-active-characters"[^>]*checked[\s\S]*包含啟用的人物/);
  assert.match(html, /id="import-video-project-dialog"[\s\S]*id="import-project-characters"[\s\S]*匯入人物並複寫/);
  assert.match(html, /id="video-resource-title">資源<\/h2>/);
  assert.match(html, /生成時只會暫存實際引用的資源，2 小時後自動刪除/);
  assert.match(html, /id="video-resource-input"[^>]*accept="image\/\*,audio\/\*,video\/\*"[^>]*multiple/);
  assert.match(html, /id="video-resource-list"/);
  assert.match(html, /id="resource-mention-menu"[^>]*aria-label="選擇資源"[^>]*hidden/);
  assert.match(html, /id="video-resource-preview-dialog"[^>]*aria-labelledby="video-resource-preview-title"/);
  assert.match(html, /id="video-prompt-preview-dialog"[^>]*aria-labelledby="video-prompt-preview-title"[\s\S]*<pre id="video-prompt-preview-text"[^>]*aria-label="目前完整題詞"[\s\S]*id="close-video-prompt-preview"/);
  assert.match(html, /id="character-template-dialog"[^>]*aria-labelledby="character-template-title"/);
  assert.match(html, /id="film-style-dialog"[^>]*aria-labelledby="film-style-title"[\s\S]*id="film-style-form"/);
  assert.match(html, /id="apply-film-style"[^>]*type="button"[^>]*>套用風格<\/button>/);
  for (const id of ["film-style-primary", "film-style-primary-custom", "film-style-era", "film-style-color", "film-style-texture", "film-style-framing", "film-style-narrator-voice", "film-style-narrator-custom", "film-style-notes"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(html, /id="film-style-primary"[\s\S]*value="電影寫實"[\s\S]*value="音樂錄影帶"[\s\S]*value="custom">自訂風格/);
  assert.match(html, /id="film-style-narrator-voice"[\s\S]*<optgroup label="女聲">[\s\S]*女聲／溫柔知性[\s\S]*<optgroup label="男聲">[\s\S]*男聲／沉穩厚實[\s\S]*value="custom">自訂聲線/);
  assert.match(html, /id="add-character"[^>]*>＋ 新增人物<\/button>/);
  assert.match(html, /id="character-editor-dialog"[^>]*aria-labelledby="character-editor-title"/);
  for (const id of ["character-name", "character-reference", "character-style", "character-tone", "character-voice", "character-voice-custom", "character-clothing", "delete-character"]) assert.ok(ids.includes(id), id);
  assert.match(html, /名字（必填）[\s\S]*id="character-name"[^>]*required/);
  assert.match(html, /參考圖（必填）[\s\S]*id="character-reference"[^>]*required/);
  assert.match(html, /id="character-reference-box"[\s\S]*id="character-reference"[\s\S]*id="character-reference-preview"[\s\S]*id="character-reference-placeholder"[\s\S]*點選選擇人物參考圖/);
  assert.match(css, /\.character-reference-box \{[^}]*aspect-ratio: 4 \/ 3/);
  assert.match(html, /id="character-reference"[\s\S]*id="character-voice"[\s\S]*id="character-voice-custom"[\s\S]*id="character-tone"[\s\S]*id="character-style"[\s\S]*id="character-clothing"/);
  assert.match(html, /id="character-voice"[\s\S]*<optgroup label="女聲">[\s\S]*女聲／溫柔知性[\s\S]*<optgroup label="男聲">[\s\S]*男聲／沉穩厚實[\s\S]*value="custom">自訂聲線/);
  assert.match(html, /id="video-prompt-builder-dialog"[^>]*aria-labelledby="video-prompt-builder-title"/);
  assert.match(html, /<h2 id="video-prompt-builder-title">分鏡內容<\/h2>/);
  assert.match(html, /id="minimize-video-prompt-builder"[^>]*>縮小<\/button>/);
  assert.match(html, /id="restore-video-prompt-builder"[^>]*hidden>[\s\S]*分鏡內容[\s\S]*繼續編輯/);
  assert.match(html, /id="video-prompt-builder-form"[\s\S]*id="submit-video-prompt-builder"[^>]*>加入分鏡<\/button>/);
  assert.match(html, /id="character-mention-menu"[^>]*role="listbox"[^>]*aria-label="選擇已啟用人物"[^>]*hidden/);
  assert.match(html, /for="video-prompt-start"><span>開始時間（秒）<\/span><input id="video-prompt-start"[^>]*type="number"[^>]*min="0"[^>]*step="0\.1"[^>]*required/);
  assert.match(html, /for="video-prompt-end"><span>結束時間（秒）<\/span><input id="video-prompt-end"[^>]*type="number"[^>]*min="0"[^>]*step="0\.1"[^>]*required/);
  for (const [id, label] of [["video-prompt-scene", "場景"], ["video-prompt-sound", "音效"]]) {
    assert.match(html, new RegExp(`<span>${label}<\\/span><div id="${id}"[^>]*resource-editor`));
  }
  assert.match(html, /<span>人物與對話<\/span>[\s\S]*id="add-video-dialogue"[^>]*>＋ 新增對話<\/button>[\s\S]*id="video-dialogue-list"/);
  assert.doesNotMatch(html, /id="video-prompt-dialogue"|<span>對白<\/span>/);
  assert.match(html, /<span>鏡頭<\/span>[\s\S]*id="video-prompt-camera"[\s\S]*<optgroup label="基本運鏡">[\s\S]*<optgroup label="跟拍與環繞">[\s\S]*<optgroup label="電影感運鏡">/);
  assert.match(html, /id="video-prompt-camera"[\s\S]*<option value="custom">自訂運鏡（開放輸入）<\/option>[\s\S]*id="video-prompt-camera-speed"/);
  assert.match(html, /id="video-prompt-camera-custom"[^>]*resource-editor[^>]*hidden/);
  assert.match(script, /function cameraPromptField\(\)[\s\S]*motion !== "custom"[\s\S]*editorText\(editor\)/);
  assert.match(html, /<span>視角<\/span>[\s\S]*id="video-prompt-shot-size"[\s\S]*大遠景[\s\S]*微距特寫/);
  assert.match(html, /id="video-prompt-view-angle"[\s\S]*<optgroup label="高度與俯仰">[\s\S]*<optgroup label="觀看方向">[\s\S]*<optgroup label="特殊視角">[\s\S]*value="custom">自訂視角（開放輸入）/);
  assert.match(html, /id="video-prompt-view-custom"[^>]*resource-editor[^>]*hidden/);
  assert.match(html, /id="video-prompt-view-subjects"[^>]*aria-label="選擇畫面主體"/);
  assert.match(html, /id="video-prompt-viewpoint-wrap"[^>]*hidden>[\s\S]*id="video-prompt-viewpoint-character"/);
  assert.match(html, /<span>動作<\/span>[\s\S]*id="video-prompt-action-character"[\s\S]*id="video-prompt-action-category"[\s\S]*基本移動[\s\S]*環境反應/);
  assert.match(html, /id="video-prompt-action-type"[^>]*disabled[\s\S]*id="video-prompt-action-style"[\s\S]*慢動作/);
  for (const id of ["video-prompt-action-custom", "video-prompt-action-target", "video-prompt-action-detail"]) assert.match(html, new RegExp(`id="${id}"[^>]*resource-editor`));
  assert.match(html, /<span>燈光<\/span>[\s\S]*id="video-prompt-lighting"[\s\S]*<optgroup label="方向與人物布光">[\s\S]*<optgroup label="自然光與環境光">[\s\S]*<optgroup label="電影風格布光">/);
  assert.match(html, /id="video-prompt-lighting"[\s\S]*<option value="custom">自訂燈光（開放輸入）<\/option>[\s\S]*id="video-prompt-lighting-temperature"[\s\S]*id="video-prompt-lighting-intensity"/);
  assert.match(html, /id="video-prompt-lighting-custom"[^>]*resource-editor[^>]*hidden/);
  assert.match(script, /function lightingPromptField\(\)[\s\S]*const prefix = `\$\{intensity\}\$\{temperature\}`[\s\S]*lighting !== "custom"/);
  assert.match(script, /function minimizeVideoPromptBuilder\(\)[\s\S]*promptBuilderMinimized = true;[\s\S]*\.close\("minimized"\)/);
  assert.match(script, /function restoreVideoPromptBuilder\(\)[\s\S]*showVideoPromptBuilder\(\)/);
  assert.match(script, /const minimized = \$\("video-prompt-builder-dialog"\)\.returnValue === "minimized";[\s\S]*\$\("open-video-prompt-builder"\)\.disabled = busy \|\| minimized/);
  assert.doesNotMatch(html, /id="video-prompt-(?:start|end)"[^>]*resource-editor/);
  assert.doesNotMatch(html, /id="video-prompt"[^>]*maxlength=/);
  assert.match(html, /id="video-resolution"/);
  assert.match(html, /id="video-duration"/);
  assert.match(html, /id="video-ratio"/);
  assert.match(html, /id="video-model"[^>]*class="setting-select"[\s\S]*value="MiniMax-H3"[^>]*selected>MiniMax H3<\/option>/);
  assert.match(html, /value="MiniMax-H3-Max">MiniMax H3 Max<\/option>/);
  assert.match(html, /value="dreamina-seedance-2-0-260128">Seedance 2\.0<\/option>\s*<option value="dreamina-seedance-2-5-260628">Seedance 2\.5<\/option>/);
  assert.match(html, /value="veo-3\.1-generate-preview">Veo 3\.1<\/option>/);
  assert.match(html, /id="video-api-key"[^>]*>未設定<\/button>/);
  assert.doesNotMatch(html, /影片模型與 API 尚未設定，後續加入模型後即可啟用生成/);
  assert.match(html, /id="generate-video"[^>]*disabled>▶ 生成影片<\/button>/);
  assert.match(html, /id="confirm-video-generation-dialog"[^>]*aria-labelledby="confirm-video-generation-title"/);
  assert.match(html, /id="confirm-video-generation-message">影片生成會消耗 MiniMax 帳戶額度，是否確定開始生成？/);
  assert.match(html, /id="cancel-video-generation"[^>]*>取消<\/button>/);
  assert.match(html, /<button class="dialog-confirm" type="submit">確認生成<\/button>/);
  assert.match(html, /id="generated-video"[^>]*controls[^>]*playsinline[^>]*hidden/);
  assert.match(html, /id="download-video"[^>]*disabled/);
  assert.match(html, /id="retry-save-video"[^>]*hidden>重新保存影片<\/button>/);
  assert.match(html, /id="apply-video-background"[^>]*disabled/);
  assert.match(css, /#video-prompt\s*\{[^}]*height:\s*560px/);
  assert.match(css, /body\.video-generator-body\s*\{[^}]*min-width:\s*1280px;[^}]*overflow-x:\s*auto/);
  assert.doesNotMatch(css, /@media \(max-width:/);
  assert.match(css, /\.video-prompt-field\s*\{[^}]*margin:\s*0/);
  assert.match(css, /\.video-collapsible-summary\s*\{[^}]*cursor:\s*pointer/);
  assert.match(css, /\.video-prompt-builder-dialog\s*\{[^}]*width:\s*1080px;[^}]*max-width:\s*none/);
  assert.match(css, /\.video-prompt-add\s*\{[^}]*border:\s*1px solid var\(--primary\)[^}]*color:\s*var\(--primary\)/);
  assert.match(css, /\.video-prompt-preview-button\s*\{[^}]*margin-right:\s*auto/);
  assert.match(css, /\.film-style-fields\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.video-prompt-preview-text\s*\{[^}]*user-select:\s*text/);
  assert.match(css, /\.video-prompt-builder-fields\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.video-prompt-builder-column\s*\{[^}]*align-content:\s*start;[^}]*gap:\s*14px/);
  assert.match(css, /\.character-mention-menu\s*\{[^}]*position:\s*fixed[^}]*max-height:\s*220px/);
  assert.match(css, /\.resource-mention-menu\s*\{[^}]*position:\s*fixed[^}]*max-height:\s*248px/);
  assert.match(css, /\.resource-token\s*\{[^}]*cursor:\s*pointer/);
  assert.match(css, /\.video-resource-list\s*\{[^}]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.character-template-list\s*\{[^}]*grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.character-template-item\s*\{[^}]*flex-direction:\s*column/);
  assert.match(css, /\.character-template-edit img,[\s\S]*?\.character-thumbnail-placeholder\s*\{[^}]*width:\s*100%[^}]*aspect-ratio:\s*4 \/ 5/);
  assert.match(css, /\.character-template-edit strong\s*\{[^}]*text-align:\s*center/);
  assert.match(css, /\.character-template-toggle\[aria-pressed="false"\]/);
  assert.match(globalCss, /\.dialog-confirm\s*\{[^}]*border:\s*1px solid var\(--primary\)[^}]*background:\s*transparent/);
  assert.match(globalCss, /\.reset-confirm\s*\{[^}]*border:\s*1px solid var\(--error\)[^}]*background:\s*transparent/);
  assert.match(css, /\.video-prompt-builder-fields \.video-prompt-action-field\s*\{[^}]*align-self:\s*start/);
  assert.match(css, /\.video-action-selects\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.video-dialogue-row\s*\{[^}]*grid-template-columns:\s*170px 180px minmax\(0, 1fr\) auto/);
  assert.match(css, /\.video-dialogue-field\s*\{[^}]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.video-view-subjects\s*\{[^}]*flex-wrap:\s*wrap/);
  assert.match(script, /applyTheme\(settings\.mode, settings\.theme\)/);
  assert.match(script, /window\.confirm\("草稿會自動保存；尚未加入分鏡的視窗內容不會保留，是否離開影片生成器？"\)/);
  assert.match(script, /window\.addEventListener\("beforeunload", event => \{\s*if \(allowPageExit\) return;\s*event\.preventDefault\(\);\s*event\.returnValue = ""/);
  assert.match(script, /allowPageExit = true;\s*window\.location\.href = "\.\/"/);
  assert.match(script, /"影片細節已輸入" : "等待輸入影片細節"/);
  assert.match(script, /function collectStoryboardDraft\(\)[\s\S]*start: \$\("video-prompt-start"\)\.value,[\s\S]*end: \$\("video-prompt-end"\)\.value,[\s\S]*shotSize:[\s\S]*viewSubjects: selectedStoryboardSubjects\(\)[\s\S]*viewpointCharacter:[\s\S]*actionCharacter:[\s\S]*actionDetail:[\s\S]*lightingIntensity:/);
  assert.match(script, /function collectStoryboardDraft\(\)[\s\S]*dialogues: collectDialogueRows\(\)/);
  assert.match(script, /function dialogueSpeakerSelect\(selected = ""\)[\s\S]*__narrator__[\s\S]*character\.enabled !== false/);
  assert.match(script, /function dialogueSpeakerSelect\(selected = ""\)[\s\S]*video-dialogue-speaker/);
  assert.match(script, /function createDialogueRow\(dialogue = \{\}\)[\s\S]*口氣／情緒[\s\S]*createElement\("input"\)[\s\S]*text\.type = "text"[\s\S]*video-dialogue-text[\s\S]*向上移動對話[\s\S]*向下移動對話[\s\S]*刪除對話/);
  assert.match(script, /function syncDialogueOrderButtons\(\)[\s\S]*data-dialogue-action="up"[\s\S]*disabled = index === 0[\s\S]*data-dialogue-action="down"[\s\S]*disabled = index === rows\.length - 1/);
  assert.match(script, /function renderDialogueRows\(dialogues = \[\]\)/);
  assert.match(script, /function escapedTextHtml\(text\)[\s\S]*holder\.textContent = text \|\| ""/);
  assert.match(script, /function arrangeVideoPromptBuilderFields\(\)[\s\S]*left\.append\([\s\S]*video-prompt-time-fields[\s\S]*video-prompt-camera-field[\s\S]*video-prompt-view-field[\s\S]*video-prompt-lighting-field[\s\S]*right\.append\([\s\S]*video-prompt-scene[\s\S]*video-prompt-action-field[\s\S]*video-prompt-sound/);
  assert.match(script, /draft\.dialogues\?\.length \? draft\.dialogues : draft\.dialogue \? \[\{ speaker: "", emotion: "", text: draft\.dialogue \}\] : \[\]/);
  assert.match(script, /function dialoguePromptField\(dialogues = \[\]\)[\s\S]*__narrator__[\s\S]*旁白[\s\S]*dialogues/);
  assert.match(script, /function validateDialogueRows\(form\)[\s\S]*請選擇說話者或旁白/);
  assert.match(script, /function renderStoryboardCharacterControls\([\s\S]*character\.enabled !== false[\s\S]*input\.type = "checkbox"[\s\S]*選擇視點角色（選填）/);
  assert.match(script, /function syncViewControls\([\s\S]*\["第一人稱視角", "越肩視角"\]\.includes\(angle\)/);
  assert.match(script, /function viewPromptField\(draft\)[\s\S]*視點角色：[\s\S]*畫面主體：[\s\S]*viewCustom/);
  assert.match(script, /const STORYBOARD_ACTIONS = Object\.freeze\(\{[\s\S]*movement:[\s\S]*gaze:[\s\S]*expression:[\s\S]*gesture:[\s\S]*object:[\s\S]*interaction:[\s\S]*environment:/);
  assert.match(script, /function syncActionControls\([\s\S]*STORYBOARD_ACTIONS\[category\][\s\S]*自訂動作（開放輸入）/);
  assert.match(script, /function actionPromptField\(draft\)[\s\S]*所有畫面人物[\s\S]*目標或物件：[\s\S]*actionDetail/);
  assert.match(script, /video-prompt-view-subjects"\)\.addEventListener\("change"[\s\S]*video-prompt-action-character"\)\.value = event\.target\.value/);
  assert.match(script, /function nextStoryboardStart\(\)[\s\S]*storyboards\.get\(last\.dataset\.storyboardId\)\?\.end \|\| "0"/);
  assert.match(script, /function formatStoryboardTime\(start, end\)[\s\S]*`\$\{Number\(start\)\}-\$\{Number\(end\)\}s`/);
  assert.match(script, /function createStoryboardBlock\(draft\)[\s\S]*storyboard-card-action[\s\S]*editStoryboard\(draft\.id\)/);
  assert.match(script, /function editStoryboard\(id\)[\s\S]*restoreEditorHtml[\s\S]*"儲存分鏡"/);
  assert.match(script, /function duplicateStoryboard\(id\)[\s\S]*structuredClone\(source\)[\s\S]*duration = Number\(source\.end\) - Number\(source\.start\)[\s\S]*copy\.start = roundedStoryboardTime\(source\.end\)[\s\S]*copy\.end = roundedStoryboardTime\(Number\(copy\.start\) \+ duration\)/);
  assert.match(script, /function deleteStoryboard\(id\)[\s\S]*確定刪除這個分鏡/);
  assert.match(script, /existing\.replaceWith\(block\)[\s\S]*refreshStoryboardLabels\(\)/);
  assert.match(script, /function validateStoryboardTimes\(form\)[\s\S]*請輸入開始時間[\s\S]*請輸入結束時間[\s\S]*Number\(endInput\.value\) <= Number\(startInput\.value\)[\s\S]*結束時間必須大於開始時間[\s\S]*form\.reportValidity\(\)/);
  assert.match(script, /if \(!validateStoryboardTimes\(event\.currentTarget\)\) return;/);
  assert.match(script, /else prompt\.append\(block\);/);
  assert.doesNotMatch(script, /prompt\.append\(block, document\.createElement\("br"\)\)/);
  assert.match(script, /"MiniMax-H3": Object\.freeze\(\{[^}]*label: "MiniMax H3"[^}]*provider: "minimax"[^}]*resolutions: \["768P", "2K"\][^}]*minimumDuration: 4[^}]*maximumDuration: 15/);
  assert.match(script, /"MiniMax-H3-Max": Object\.freeze\(\{[^}]*label: "MiniMax H3 Max"[^}]*provider: "minimax"[^}]*resolutions: \["480P", "768P"\][^}]*defaultResolution: "480P"[^}]*minimumDuration: 5[^}]*maximumDuration: 15/);
  assert.match(script, /"dreamina-seedance-2-0-260128": Object\.freeze\(\{[^}]*label: "Seedance 2\.0"[^}]*provider: "byteplus"[^}]*resolutions: \["480p", "720p", "1080p", "4k"\][^}]*defaultResolution: "480p"[^}]*minimumDuration: 4[^}]*maximumDuration: 15/);
  assert.match(script, /"dreamina-seedance-2-5-260628": Object\.freeze\(\{[^}]*label: "Seedance 2\.5"[^}]*provider: "byteplus"[^}]*resolutions: \["480p", "720p"\][^}]*defaultResolution: "480p"[^}]*minimumDuration: 4[^}]*maximumDuration: 30/);
  assert.match(script, /"veo-3\.1-generate-preview": Object\.freeze\(\{[^}]*label: "Veo 3\.1"[^}]*provider: "google"[^}]*apiKey: "Google AI Studio"[^}]*resolutions: \["720p", "1080p"\][^}]*durations: \[4, 6, 8\][^}]*ratios: \["16:9", "9:16"\]/);
  assert.match(script, /saveApiKey\(modelId, model\.label, value\)/);
  assert.match(script, /listApiKeys\(\)\.filter\(key => key\.id !== modelId\)/);
  assert.match(html, /id="video-api-key-dialog"/);
  assert.match(html, /id="google-quota-help"[^>]*hidden>[\s\S]*aistudio\.google\.com\/rate-limit[\s\S]*ai\.google\.dev\/gemini-api\/docs\/billing/);
  assert.match(script, /https:\/\/model-proxy\.yustellar\.idv\.tw\/minimax\/video/);
  assert.match(script, /CREATE_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /QUERY_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /DOWNLOAD_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /https:\/\/model-proxy\.yustellar\.idv\.tw\/byteplus\/video/);
  assert.match(script, /BYTEPLUS_CREATE_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /BYTEPLUS_QUERY_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /BYTEPLUS_DOWNLOAD_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /GOOGLE_VIDEO_PROXY_URL = "https:\/\/model-proxy\.yustellar\.idv\.tw\/google\/video"/);
  assert.match(script, /GOOGLE_CREATE_VIDEO_URL = `\$\{GOOGLE_VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /GOOGLE_QUERY_VIDEO_URL = `\$\{GOOGLE_VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /GOOGLE_DOWNLOAD_VIDEO_URL = `\$\{GOOGLE_VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /model\.durations \|\| Array\.from/);
  assert.match(script, /const ratios = model\.ratios \|\| VIDEO_RATIOS/);
  assert.match(script, /model\.provider === "google"[\s\S]*Google AI Studio Gemini API KEY/);
  assert.match(script, /RESOURCE_UPLOAD_URL = "https:\/\/model-proxy\.yustellar\.idv\.tw\/resources\/upload"/);
  assert.match(script, /function referencedCharacters\(videoDetails\)[\s\S]*videoDetails\.includes\(character\.name\)/);
  assert.match(script, /function filmStyleText\(\)[\s\S]*主要風格[\s\S]*畫面比例感[\s\S]*旁白聲線[\s\S]*全片風格：/);
  assert.match(script, /function characterTemplateText\(characters\)[\s\S]*人物設定：/);
  assert.match(script, /function videoPromptSections\(\)[\s\S]*\.storyboard-block[\s\S]*storyboards:/);
  assert.match(script, /function resourceReferenceText\(\)[\s\S]*引用資源：/);
  assert.match(script, /function completeVideoPrompt\(videoDetails = editorText\(\$\("video-prompt"\)\)\)[\s\S]*filmStyleText\(\),[\s\S]*characterTemplateText\(referencedCharacters\(videoDetails\)\),[\s\S]*影片細節：[\s\S]*分鏡內容：[\s\S]*resourceReferenceText\(\)/);
  assert.match(script, /function openVideoPromptPreview\(\)[\s\S]*video-prompt-preview-text"\)\.textContent = completeVideoPrompt\(\)[\s\S]*showModal\(\)/);
  assert.match(script, /const prompt = completeVideoPrompt\(videoDetails\)/);
  assert.match(script, /function explainRejectedReference\(message, inputs\)[\s\S]*content\\\[\(\\d\+\)\\\][\s\S]*inputs\[contentIndex - 1\][\s\S]*圖片可能包含真人/);
  assert.match(script, /explainRejectedReference\(error\.message \|\| "影片生成失敗。", inputs\)/);
  assert.match(script, /function referencedResources\(\)[\s\S]*video-prompt"\)\.querySelectorAll\("\.resource-token"\)/);
  assert.match(script, /referenceName: `人物「\$\{character\.name\}」`/);
  assert.match(script, /async function uploadGenerationInputs\(inputs, signal\)/);
  assert.match(script, /body: input\.file/);
  assert.match(script, /role: modelId === "MiniMax-H3-Max" \? "first_frame" : `reference_\$\{input\.kind\}`/);
  assert.match(script, /referenceImages = await Promise\.all/);
  assert.match(script, /image: \{ inlineData: \{ mimeType: resourceMimeType\(input\), data: await fileBase64\(input\.file\) \} \}/);
  assert.match(script, /Veo 3\.1 最多可使用 3 張引用圖片（包含人物參考圖）/);
  assert.doesNotMatch(script, /AUTOCOMPLETE_URL|requestCompletedPrompt|enhance-video-prompt/);
  assert.match(script, /JSON\.stringify\(\{ apiKey, taskId \}\)/);
  assert.match(script, /body: JSON\.stringify\(\{\s*apiKey,\s*payload,/);
  assert.match(script, /fetch\(providerEndpoints\(provider\)\.download, \{[\s\S]*body: JSON\.stringify\(\{ url: remoteUrl, \.\.\.\(provider === "google" \? \{ apiKey \} : \{\}\) \}\)/);
  assert.match(script, /function videoFilename\(date = new Date\(\)\)/);
  assert.match(script, /return `video_\$\{day\}_\$\{time\}\.mp4`/);
  assert.match(script, /code === 1008 \|\| \/insufficient balance\/i\.test\(message\)/);
  assert.match(script, /目前 MiniMax API KEY 所屬帳戶餘額不足（1008），請充值或更換 API KEY。/);
  assert.match(script, /code === 2013 && \/TokenPlan\|Credit\.\*MiniMax-H3\/i\.test\(message\)/);
  assert.match(script, /目前使用的 MiniMax Token Plan／Credit Key 不支援 H3 系列（2013）/);
  assert.match(script, /provider === "google" && \(code === 429 \|\| \/RESOURCE_EXHAUSTED\|quota\|rate limit\/i\.test\(message\)\)/);
  assert.match(script, /Google Veo 額度或速率限制已用盡（429）/);
  assert.match(script, /google-quota-help"\)\.hidden = !text\.includes\("Google Veo 額度或速率限制"\)/);
  assert.match(html, /MiniMax H3 系列須使用一般 Pay-as-you-go API KEY；Token Plan／Credit Key 不支援/);
  assert.match(script, /apiError\(body, response\.ok \? "" : `\$\{service\} API 回傳 \$\{response\.status\}`, provider\)/);
  assert.match(script, /async function pollVideoTask\(taskId, apiKey, model, signal\)/);
  assert.match(script, /model\.provider === "byteplus" \? created\?\.id : model\.provider === "google" \? created\?\.name : created\?\.task_id/);
  assert.match(script, /model\.provider === "byteplus" \? task\.content\?\.video_url : task\.content\?\.url/);
  assert.match(script, /task\.response\?\.generateVideoResponse\?\.generatedSamples\?\.\[0\]\?\.video\?\.uri/);
  assert.match(script, /payload\.generate_audio = true/);
  assert.match(script, /payload\.watermark = false/);
  assert.match(script, /instances: \[\{ prompt: guidedPrompt,[\s\S]*sampleCount: 1[\s\S]*durationSeconds:[\s\S]*aspectRatio:/);
  assert.match(script, /provider === "google" \? \{ apiKey \} : \{\}/);
  assert.match(script, /generate-video"\)\.addEventListener\("click", openGenerateConfirmation\)/);
  assert.match(script, /confirm-video-generation-form"\)\.addEventListener\("submit", confirmVideoGeneration\)/);
  assert.match(script, /taskState === "succeeded"/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.match(script, /saveStoredMedia\("generated-video", cachedFile\)/);
  assert.match(script, /retry-save-video"\)\.addEventListener\("click", async \(\) =>/);
  assert.match(script, /loadStoredMedia\("generated-video"\)/);
  assert.match(script, /void restoreLastGeneratedVideo\(\)/);
  assert.match(script, /showVideoResult\(task\.videoUrl, model\.provider, true, apiKey\)/);
  assert.match(script, /if \(expandResult\) \$\("video-result-panel"\)\.open = true/);
  assert.match(script, /saveStoredValue\("video-character-templates", \{ characters: characterTemplates, updatedAt: Date\.now\(\) \}\)/);
  assert.match(script, /loadStoredValue\("video-character-templates"\)/);
  assert.match(script, /window\.confirm\(`確定刪除「\$\{name\}」？刪除後將同步移除保存的人物模板。`\)/);
  assert.match(script, /editButton\.addEventListener\("click", \(\) => openCharacterEditor\(index\)\)/);
  assert.match(script, /function setCharacterVoice\(value = ""\)[\s\S]*presetExists[\s\S]*"custom"[\s\S]*character-voice-custom/);
  assert.match(script, /function showCharacterEditorReference\(file\)[\s\S]*character-reference-placeholder[\s\S]*classList\.add\("has-image"\)/);
  assert.match(script, /function videoProjectMetadata\(includeCharacters, binaries\)[\s\S]*videoDetailsHtml[\s\S]*storyboards:[\s\S]*resources:[\s\S]*characters:[\s\S]*generation:/);
  assert.match(html, /id="video-auto-draft-status"[^>]*>正在檢查自動儲存草稿…<\/span>/);
  assert.match(script, /saveStoredValue\("video-generator-draft"/);
  assert.match(script, /saveStoredValue\("video-generator-draft-resources"/);
  assert.match(script, /loadStoredValue\("video-generator-draft"\)/);
  assert.match(script, /async function exportVideoProject\(event\)[\s\S]*await saveAutoDraftNow\(\{ resources: true \}\)[\s\S]*await projectFromStoredDraft\(includeCharacters\)[\s\S]*createVideoProjectFile/);
  assert.match(script, /function sanitizedImportedHtml\(html\)[\s\S]*resource-token[\s\S]*createResourceMention/);
  assert.match(script, /async function importVideoProject\(event\)[\s\S]*persistCharacterTemplates[\s\S]*renderVideoResources[\s\S]*createStoryboardBlock/);
  assert.match(script, /function characterVoiceValue\(\)[\s\S]*character-voice-custom/);
  assert.match(script, /voice: characterVoiceValue\(\)/);
  assert.match(script, /toggle\.addEventListener\("click", \(\) => void toggleCharacterTemplate\(index\)\)/);
  assert.match(script, /toggle\.textContent = character\.enabled === false \? "啟用" : "禁用"/);
  assert.match(script, /enabled:\s*editingCharacterIndex >= 0 \? characterTemplates\[editingCharacterIndex\]\?\.enabled !== false : false/);
  assert.match(script, /characterTemplates\.filter\(character => character\.enabled !== false\)/);
  assert.match(script, /characterTemplates\.filter\(character => character\.enabled !== false && character\.name\)/);
  assert.doesNotMatch(script, /character-mention-avatar|character\.name\.slice\(0, 1\)/);
  assert.match(script, /replaceMentionText\(characterMentionMatch, document\.createTextNode\(name\)\)/);
  assert.match(script, /editor\.addEventListener\("input", handleResourceEditorInput\)/);
  assert.match(script, /function handleResourceEditorInput\(event\)[\s\S]*showCharacterMentionMenu\(target\)/);
  assert.doesNotMatch(script, /if \(target\.closest\("#video-prompt-builder-dialog"\)\) showCharacterMentionMenu/);
  assert.match(script, /const menuHost = target\.closest\("dialog"\) \|\| document\.body;[\s\S]*menuHost\.append\(menu\)/);
  assert.match(script, /event\.key === "ArrowDown" \|\| event\.key === "ArrowUp"/);
  assert.match(script, /if \(!character\.name \|\| !character\.referenceImage\)/);
  assert.match(script, /\["聲線", character\.voice\],[\s\S]*\["口氣", character\.tone\],[\s\S]*\["風格", character\.style\]/);
  assert.match(script, /const generation = generationInputs\(videoDetails\);\s*inputs = generation\.resources;\s*const prompt = completeVideoPrompt\(videoDetails\)/);
  assert.doesNotMatch(script, /saveStoredValue\("video-generation-resources"|loadStoredValue\("video-generation-resources"/);
  assert.match(script, /createResourceMention\(resource\)/);
  const mentionStart = script.indexOf("function createResourceMention(resource)");
  const mentionEnd = script.indexOf("\nfunction selectResourceMention", mentionStart);
  const mentionFunction = script.slice(mentionStart, mentionEnd);
  assert.match(mentionFunction, /document\.createElement\("span"\)/);
  assert.match(mentionFunction, /mention\.setAttribute\("role", "button"\)/);
  assert.doesNotMatch(mentionFunction, /document\.createElement\("button"\)/);
  assert.match(script, /event\.target\.matches\?\.\("\.resource-token"\) \? event\.target : null/);
  assert.match(script, /openResourcePreview\(token\.dataset\.resourceId\)/);
  assert.match(script, /function removeResourceMention\(token, editor = token\.closest\("\.resource-editor"\)\)/);
  assert.match(script, /function resourceMentionBesideCaret\(editor, direction\)/);
  assert.match(script, /\["Backspace", "Delete"\]\.includes\(event\.key\)/);
  assert.match(script, /if \(removeResourceMentionAtCaret\(event, editor\)\) return/);
  assert.match(script, /video-settings-panel"\)\.addEventListener\("toggle",[\s\S]*video-description-panel"\)\.open = false/);
  assert.match(script, /video-description-panel"\)\.addEventListener\("toggle",[\s\S]*video-settings-panel"\)\.open = false;[\s\S]*video-result-panel"\)\.open = false/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  assert.match(readFileSync("index.html", "utf8"), /href="\.\/video-generator\.html"[^>]*>影片生成器<\/a>/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"video-generator\.html"/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"video-generator\.html"/);
});
