import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

test("video generator page provides a model-ready generation workspace", () => {
  const html = readFileSync("video-generator.html", "utf8");
  const script = readFileSync("js/video-generator.js", "utf8");
  const css = readFileSync("css/video-generator.css", "utf8");
  const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  for (const [, id] of script.matchAll(/\$\("([^"]+)"\)/g)) assert.ok(ids.includes(id), id);
  for (const [, path] of html.matchAll(/(?:src|href)="\.\/([^"#?]+)(?:\?[^"#]*)?"/g)) assert.ok(existsSync(path), path);
  assert.match(html, /<title>影像產生器 · YuMeew<\/title>/);
  assert.match(html, /<meta name="viewport" content="width=1280" \/>/);
  assert.doesNotMatch(html, /video-keywords|compose-video-prompt|題詞詞語|enhance-video-prompt|文字轉譯成 Prompt/);
  assert.match(html, /<textarea id="video-prompt"[^>]*aria-label="影片細節"/);
  assert.doesNotMatch(html, />影片描述<\/label>|加入影片描述|等待輸入影片描述/);
  assert.match(html, /<details id="video-description-panel" class="panel prompt-panel video-description-panel" open>[\s\S]*<summary[^>]*>影片細節<\/summary>[\s\S]*id="video-prompt"[\s\S]*<\/details>\s*<details id="video-settings-panel" class="panel prompt-panel video-settings-panel">/);
  assert.match(html, /<summary class="video-collapsible-summary">生成設定<\/summary>/);
  assert.match(html, /<details id="video-result-panel" class="panel result-panel video-result-panel">[\s\S]*生成結果[\s\S]*<\/details>/);
  assert.doesNotMatch(html, /<details id="(?:video-settings-panel|video-result-panel)"[^>]*\sopen(?:\s|>)/);
  assert.match(html, /id="open-video-prompt-builder"[^>]*>增加場景<\/button>/);
  assert.match(html, /id="open-character-template"[^>]*>人物模板<\/button>/);
  assert.match(html, /id="character-template-dialog"[^>]*aria-labelledby="character-template-title"/);
  assert.match(html, /id="add-character"[^>]*>＋ 新增人物<\/button>/);
  assert.match(html, /id="video-prompt-builder-dialog"[^>]*aria-labelledby="video-prompt-builder-title"/);
  assert.match(html, /for="video-prompt-time"><span>時間<\/span>/);
  assert.match(html, /for="video-prompt-scene"><span>場景<\/span>/);
  assert.match(html, /for="video-prompt-camera"><span>鏡頭<\/span>/);
  assert.match(html, /for="video-prompt-view"><span>視角<\/span>/);
  assert.match(html, /for="video-prompt-lighting"><span>燈光<\/span>/);
  assert.match(html, /for="video-prompt-sound"><span>音效<\/span>/);
  assert.match(html, /for="video-prompt-action"><span>動作<\/span>/);
  assert.match(html, /for="video-prompt-dialogue"><span>對白<\/span>/);
  assert.doesNotMatch(html, /<textarea id="video-prompt"[^>]*maxlength=/);
  assert.match(html, /id="video-resolution"/);
  assert.match(html, /id="video-duration"/);
  assert.match(html, /id="video-ratio"/);
  assert.match(html, /id="video-model"[^>]*class="setting-select"[\s\S]*value="MiniMax-H3"[^>]*selected>MiniMax H3<\/option>/);
  assert.match(html, /value="MiniMax-H3-Max">MiniMax H3 Max<\/option>/);
  assert.match(html, /value="dreamina-seedance-2-0-260128">Seedance 2\.0<\/option>\s*<option value="dreamina-seedance-2-5-260628">Seedance 2\.5<\/option>/);
  assert.match(html, /id="video-api-key"[^>]*>未設定<\/button>/);
  assert.doesNotMatch(html, /影片模型與 API 尚未設定，後續加入模型後即可啟用生成/);
  assert.match(html, /id="generate-video"[^>]*disabled>▶ 生成影片<\/button>/);
  assert.match(html, /id="confirm-video-generation-dialog"[^>]*aria-labelledby="confirm-video-generation-title"/);
  assert.match(html, /id="confirm-video-generation-message">影片生成會消耗 MiniMax 帳戶額度，是否確定開始生成？/);
  assert.match(html, /id="cancel-video-generation"[^>]*>取消<\/button>/);
  assert.match(html, /<button class="dialog-confirm" type="submit">確認生成<\/button>/);
  assert.match(html, /id="generated-video"[^>]*controls[^>]*playsinline[^>]*hidden/);
  assert.match(html, /id="download-video"[^>]*disabled/);
  assert.match(html, /id="retry-save-video"[^>]*hidden>重新保存影片<\/button>/);
  assert.match(html, /id="apply-video-background"[^>]*disabled/);
  assert.match(css, /#video-prompt\s*\{[^}]*height:\s*560px/);
  assert.match(css, /body\.video-generator-body\s*\{[^}]*min-width:\s*1280px;[^}]*overflow-x:\s*auto/);
  assert.doesNotMatch(css, /@media \(max-width:/);
  assert.match(css, /\.video-prompt-field\s*\{[^}]*margin:\s*0/);
  assert.match(css, /\.video-collapsible-summary\s*\{[^}]*cursor:\s*pointer/);
  assert.match(css, /\.video-prompt-builder-dialog\s*\{[^}]*width:\s*min\(820px, calc\(100vw - 80px\)\)/);
  assert.match(css, /\.video-prompt-builder-fields\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /label\[for="video-prompt-action"\]\s*\{[^}]*align-self:\s*start/);
  assert.match(script, /applyTheme\(settings\.mode, settings\.theme\)/);
  assert.match(script, /"影片細節已輸入" : "等待輸入影片細節"/);
  assert.match(script, /const fields = \[\s*\["時間"[^\]]*\],\s*\["場景"[^\]]*\],\s*\["鏡頭"[^\]]*\],\s*\["視角"[^\]]*\],\s*\["燈光"[^\]]*\],\s*\["音效"[^\]]*\],\s*\["動作"[^\]]*\],\s*\["對白"[^\]]*\]/);
  assert.match(script, /prompt\.value = prompt\.value\.trim\(\) \? `\$\{prompt\.value\.trimEnd\(\)\}\\n\\n\$\{block\}\\n\\n` : `\$\{block\}\\n\\n`/);
  assert.match(script, /"MiniMax-H3": Object\.freeze\(\{[^}]*label: "MiniMax H3"[^}]*provider: "minimax"[^}]*resolutions: \["768P", "2K"\][^}]*minimumDuration: 4[^}]*maximumDuration: 15/);
  assert.match(script, /"MiniMax-H3-Max": Object\.freeze\(\{[^}]*label: "MiniMax H3 Max"[^}]*provider: "minimax"[^}]*resolutions: \["480P", "768P"\][^}]*defaultResolution: "480P"[^}]*minimumDuration: 5[^}]*maximumDuration: 15/);
  assert.match(script, /"dreamina-seedance-2-0-260128": Object\.freeze\(\{[^}]*label: "Seedance 2\.0"[^}]*provider: "byteplus"[^}]*resolutions: \["480p", "720p", "1080p", "4k"\][^}]*defaultResolution: "480p"[^}]*minimumDuration: 4[^}]*maximumDuration: 15/);
  assert.match(script, /"dreamina-seedance-2-5-260628": Object\.freeze\(\{[^}]*label: "Seedance 2\.5"[^}]*provider: "byteplus"[^}]*resolutions: \["480p", "720p"\][^}]*defaultResolution: "480p"[^}]*minimumDuration: 4[^}]*maximumDuration: 30/);
  assert.match(script, /saveApiKey\(modelId, model\.label, value\)/);
  assert.match(script, /listApiKeys\(\)\.filter\(key => key\.id !== modelId\)/);
  assert.match(html, /id="video-api-key-dialog"/);
  assert.match(script, /https:\/\/model-proxy\.yustellar\.idv\.tw\/minimax\/video/);
  assert.match(script, /CREATE_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /QUERY_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /DOWNLOAD_VIDEO_URL = `\$\{VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /https:\/\/model-proxy\.yustellar\.idv\.tw\/byteplus\/video/);
  assert.match(script, /BYTEPLUS_CREATE_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/generate`/);
  assert.match(script, /BYTEPLUS_QUERY_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/query`/);
  assert.match(script, /BYTEPLUS_DOWNLOAD_VIDEO_URL = `\$\{BYTEPLUS_VIDEO_PROXY_URL\}\/download`/);
  assert.match(script, /content: \[\{ type: "text", text: prompt \}\]/);
  assert.doesNotMatch(script, /AUTOCOMPLETE_URL|requestCompletedPrompt|enhance-video-prompt/);
  assert.match(script, /JSON\.stringify\(\{ apiKey, taskId \}\)/);
  assert.match(script, /body: JSON\.stringify\(\{\s*apiKey,\s*payload,/);
  assert.match(script, /fetch\(providerEndpoints\(provider\)\.download, \{[\s\S]*body: JSON\.stringify\(\{ url: remoteUrl \}\)/);
  assert.match(script, /function videoFilename\(date = new Date\(\)\)/);
  assert.match(script, /return `video_\$\{day\}_\$\{time\}\.mp4`/);
  assert.match(script, /code === 1008 \|\| \/insufficient balance\/i\.test\(message\)/);
  assert.match(script, /目前 MiniMax API KEY 所屬帳戶餘額不足（1008），請充值或更換 API KEY。/);
  assert.match(script, /code === 2013 && \/TokenPlan\|Credit\.\*MiniMax-H3\/i\.test\(message\)/);
  assert.match(script, /目前使用的 MiniMax Token Plan／Credit Key 不支援 H3 系列（2013）/);
  assert.match(html, /MiniMax H3 系列須使用一般 Pay-as-you-go API KEY；Token Plan／Credit Key 不支援/);
  assert.match(script, /apiError\(body, response\.ok \? "" : `\$\{service\} API 回傳 \$\{response\.status\}`, provider\)/);
  assert.match(script, /async function pollVideoTask\(taskId, apiKey, model, signal\)/);
  assert.match(script, /model\.provider === "byteplus" \? created\?\.id : created\?\.task_id/);
  assert.match(script, /model\.provider === "byteplus" \? task\.content\?\.video_url : task\.content\?\.url/);
  assert.match(script, /payload\.generate_audio = true/);
  assert.match(script, /payload\.watermark = false/);
  assert.match(script, /generate-video"\)\.addEventListener\("click", openGenerateConfirmation\)/);
  assert.match(script, /confirm-video-generation-form"\)\.addEventListener\("submit", confirmVideoGeneration\)/);
  assert.match(script, /taskState === "succeeded"/);
  assert.match(script, /saveStoredMedia\("image", file\)/);
  assert.match(script, /saveStoredMedia\("generated-video", cachedFile\)/);
  assert.match(script, /retry-save-video"\)\.addEventListener\("click", async \(\) =>/);
  assert.match(script, /loadStoredMedia\("generated-video"\)/);
  assert.match(script, /void restoreLastGeneratedVideo\(\)/);
  assert.match(script, /showVideoResult\(task\.videoUrl, model\.provider, true\)/);
  assert.match(script, /if \(expandResult\) \$\("video-result-panel"\)\.open = true/);
  assert.match(script, /saveStoredValue\("video-character-templates", \{ characters: characterTemplates, updatedAt: Date\.now\(\) \}\)/);
  assert.match(script, /loadStoredValue\("video-character-templates"\)/);
  assert.match(script, /window\.confirm\(`確定刪除「\$\{name\}」？刪除後將同步移除保存的人物模板。`\)/);
  assert.match(script, /const prompt = \[videoDetails, characterTemplateText\(\)\]\.filter\(Boolean\)\.join\("\\n\\n"\)/);
  assert.match(script, /video-settings-panel"\)\.addEventListener\("toggle",[\s\S]*video-description-panel"\)\.open = false/);
  assert.match(script, /deleteStoredValue\("image-video-project"\)/);
  assert.match(readFileSync("index.html", "utf8"), /href="\.\/video-generator\.html"[^>]*>影像產生器<\/a>/);
  assert.match(readFileSync("scripts/build.js", "utf8"), /"video-generator\.html"/);
  assert.match(readFileSync("scripts/serve.js", "utf8"), /"video-generator\.html"/);
});
